name: 🐞 Bug
description: Report a bug in the site
title: "[BUG]: "
assignees:
  - kevin8181
body:
  - type: textarea
    id: comment
    attributes:
      label: Comment
      description: Describe the bug
